export const tourDates = [
  {
    date: "2026-09-29",
    city: "San Antonio",
    venue: "Alamodome",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-26",
    city: "Los Angeles",
    venue: "BMO Stadium",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-25",
    city: "Los Angeles",
    venue: "BMO Stadium",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-22",
    city: "Tinley Park",
    venue: "Credit Union 1 Amphitheatre",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-19",
    city: "Shakopee",
    venue: "Mystic Lake Amphitheater",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-15",
    city: "Hershey",
    venue: "Hersheypark Stadium",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-12",
    city: "Charlotte",
    venue: "PNC Music Pavilion",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-11",
    city: "Bristow",
    venue: "Jiffy Lube Live",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-09",
    city: "Boston",
    venue: "TD Garden",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-06",
    city: "Harrison",
    venue: "Sports Illustrated Stadium",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-05",
    city: "Harrison",
    venue: "Sports Illustrated Stadium",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-09-03",
    city: "Montréal",
    venue: "Parc Jean Drapeau",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-08-30",
    city: "Toronto",
    venue: "Scotiabank Arena",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-08-29",
    city: "Toronto",
    venue: "Scotiabank Arena",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-28",
    city: "Almaty",
    venue: "Spartak Stadium",
    country: "Kazakhstan",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-26",
    city: "Helsinki",
    venue: "Suvilahti - TUSKA",
    country: "Finland",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-23",
    city: "Istanbul",
    venue: "Kucukciftlik Park",
    country: "Turkey",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-20",
    city: "Clisson",
    venue: "Hellfest",
    country: "France",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-18",
    city: "Dessel",
    venue: "Graspop Metal Meeting",
    country: "Belgium",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-16",
    city: "Vienna",
    venue: "Gasometer",
    country: "Austria",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-15",
    city: "Zurich",
    venue: "Halle 622",
    country: "Switzerland",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-14",
    city: "Ferrara",
    venue: "Ferrara Summer Festival - Piazza Ariostea",
    country: "Italy",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-11",
    city: "Esch-Sur-Alzette",
    venue: "Rockhal",
    country: "Luxembourg",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-10",
    city: "Hradec Králové",
    venue: "Rock For People - Park 360",
    country: "Czechia",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-07",
    city: "Gelsenkirchen",
    venue: "Amphitheater",
    country: "Germany",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-06",
    city: "Maastricht",
    venue: "South Of Heaven",
    country: "Netherlands",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-06-02",
    city: "Hanover",
    venue: "Heinz Von Heiden Arena",
    country: "Germany",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2025-10-28",
    city: "Glasgow",
    venue: "OVO Hydro",
    country: "United Kingdom",
    ticketLink: "https://www.ticketmaster.co.uk",
  },
  {
    date: "2025-10-26",
    city: "London",
    venue: "The O2 Arena",
    country: "United Kingdom",
    ticketLink: "https://www.ticketmaster.co.uk",
  },
  {
    date: "2025-10-24",
    city: "Manchester",
    venue: "AO Arena",
    country: "United Kingdom",
    ticketLink: "https://www.ticketmaster.co.uk",
  },
  {
    date: "2025-10-22",
    city: "Dublin",
    venue: "3Arena",
    country: "Ireland",
    ticketLink: "https://www.ticketmaster.ie",
  },
  {
    date: "2025-10-20",
    city: "Birmingham",
    venue: "Utilita Arena",
    country: "United Kingdom",
    ticketLink: "https://www.ticketmaster.co.uk",
  },
  {
    date: "2025-10-18",
    city: "Berlin",
    venue: "Velodrome",
    country: "Germany",
    ticketLink: "https://www.ticketmaster.de",
  },
  {
    date: "2025-10-17",
    city: "Munich",
    venue: "Olympiahalle",
    country: "Germany",
    ticketLink: "https://www.ticketmaster.de",
  },
  {
    date: "2025-10-15",
    city: "Brussels",
    venue: "Forest National",
    country: "Belgium",
    ticketLink: "https://www.ticketmaster.be",
  },
  {
    date: "2025-10-14",
    city: "Amsterdam",
    venue: "Ziggo Dome",
    country: "Netherlands",
    ticketLink: "https://www.ticketmaster.nl",
  },
  {
    date: "2025-10-12",
    city: "Paris",
    venue: "Zenith",
    country: "France",
    ticketLink: "https://www.ticketmaster.fr",
  },
  {
    date: "2025-10-10",
    city: "Kraków",
    venue: "TAURON Arena",
    country: "Poland",
    ticketLink: "https://www.ticketmaster.pl",
  },
  {
    date: "2025-10-07",
    city: "Prague",
    venue: "O2 Arena",
    country: "Czech Republic",
    ticketLink: "https://www.ticketmaster.cz",
  },
  {
    date: "2025-10-06",
    city: "Budapest",
    venue: "Budapest Arena",
    country: "Hungary",
    ticketLink: "https://funcode.hu/en/event/1427-disturbed-the-sickness-25th-anniversary-tour",
  },
  {
    date: "2025-10-04",
    city: "Zurich",
    venue: "Hallenstadion",
    country: "Switzerland",
    ticketLink: "https://www.ticketmaster.ch",
  },
  {
    date: "2026-04-23",
    city: "Lima",
    venue: "Costa 21",
    country: "Peru",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-04-27",
    city: "Bogota",
    venue: "Movistar Arena",
    country: "Colombia",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-04-26",
    city: "Bogota",
    venue: "Movistar Arena",
    country: "Colombia",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-04-30",
    city: "Buenos Aires",
    venue: "Tecnopolis",
    country: "Argentina",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-05-02",
    city: "São Paulo",
    venue: "Espaço Unimed",
    country: "Brazil",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-05-05",
    city: "Santiago",
    venue: "Movistar Arena",
    country: "Chile",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-05-04",
    city: "Santiago",
    venue: "Movistar Arena",
    country: "Chile",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-05-08",
    city: "Monterrey",
    venue: "Arena Monterrey",
    country: "Mexico",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-05-11",
    city: "Mexico City",
    venue: "Arena Ciudad De Mexico",
    country: "Mexico",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-05-10",
    city: "Mexico City",
    venue: "Arena Ciudad De Mexico",
    country: "Mexico",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-05-13",
    city: "Guadalajara",
    venue: "Arena Guadalajara",
    country: "Mexico",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-02-15",
    city: "Victoria, BC",
    venue: "Save-On-Foods Memorial Centre",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-01-17",
    city: "La Vergne",
    venue: "Let There Be Shred: Immersive Listening Event",
    country: "United States",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-02-17",
    city: "Abbotsford, BC",
    venue: "Rogers Forum",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-02-18",
    city: "Kelowna, BC",
    venue: "Prospera Place",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-02-20",
    city: "Calgary, AB",
    venue: "Scotiabank Saddledome",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-02-21",
    city: "Edmonton, AB",
    venue: "Rogers Place",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-02-24",
    city: "Saskatoon, SK",
    venue: "SaskTel Centre",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-02-25",
    city: "Winnipeg, MB",
    venue: "Canada Life Centre",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-02-28",
    city: "London, ON",
    venue: "Canada Life Place",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-03-01",
    city: "Ottawa, ON",
    venue: "Canadian Tire Centre",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-03-03",
    city: "Halifax, NS",
    venue: "Scotiabank Centre",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-03-04",
    city: "Moncton, NB",
    venue: "Avenir Centre",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
  {
    date: "2026-03-06",
    city: "Québec City, QC",
    venue: "Videotron Centre",
    country: "Canada",
    ticketLink: "https://www.taylorswift.com/tour",
  },
];
